######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 02:02:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . obs
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
INCLUDEPATH += /usr/include/poppler/qt4
LIBS += -L/usr/lib -lpoppler-qt4
